packages:
  - examples/*
  - packages/*
  - plugins/*
catalog:
  "@changesets/cli": ^2.29.6
  "@eslint/js": ^9.34.0
  "@nx/eslint": ^21.4.1
  "@nx/js": ^21.4.1
  "@nx/rollup": ^21.4.1
  "@nx/vite": ^21.4.1
  "@playwright/test": ^1.55.0
  "@rollup/plugin-commonjs": ^28.0.6
  "@rollup/plugin-node-resolve": ^16.0.1
  "@rollup/plugin-typescript": ^12.1.4
  "@tanstack/devtools": ^0.6.6
  "@types/react": ^19.1.12
  "@types/react-dom": ^19.1.9
  "@typescript-eslint/eslint-plugin": ^8.42.0
  "@typescript-eslint/parser": ^8.42.0
  "@vitejs/plugin-react": ^5.0.2
  "@sucoza/accessibility-devtools-plugin": ^0.1.9
  "@sucoza/auth-permissions-mock-devtools-plugin": ^0.1.9
  "@sucoza/browser-automation-test-recorder-devtools-plugin": ^0.1.9
  "@sucoza/bundle-impact-analyzer-devtools-plugin": ^0.1.9
  "@sucoza/design-system-inspector-devtools-plugin": ^0.1.9
  "@sucoza/feature-flag-manager-devtools-plugin": ^0.1.9
  "@sucoza/form-state-inspector-devtools-plugin": ^0.1.9
  "@sucoza/memory-performance-profiler-devtools-plugin": ^0.1.9
  "@sucoza/render-waste-detector-devtools-plugin": ^0.1.9
  "@sucoza/security-audit-panel-devtools-plugin": ^0.1.9
  "@sucoza/visual-regression-monitor-devtools-plugin": ^0.1.9
  "@tanstack/devtools-event-bus": ^0.3.1
  "@tanstack/devtools-event-client": ^0.2.3
  "@tanstack/react-devtools": ^0.6.2
  "@testing-library/jest-dom": ^6.8.0
  "@testing-library/react": ^16.3.0
  "@testing-library/user-event": ^14.6.1
  "@types/chrome-remote-interface": ^0.31.14
  "@types/d3": ^7.4.3
  "@types/lodash": ^4.17.20
  "@types/node": ^24.3.0
  "@types/pixelmatch": ^5.2.6
  "@types/use-sync-external-store": ^1.5.0
  "@vitest/coverage-v8": ^3.2.4
  "@vitest/ui": ^3.2.4
  audit-ci: ^7.1.0
  autoprefixer: ^10.4.21
  axe-core: ^4.10.3
  chrome-remote-interface: ^0.33.3
  clsx: ^2.1.1
  colorjs.io: ^0.5.2
  concurrently: ^9.2.1
  cross-env: ^10.0.0
  d3: ^7.9.0
  eslint: ^9.35.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  globals: ^16.3.0
  graphql-ws: ^6.0.6
  jest: ^30.1.3
  jest-environment-jsdom: ^30.1.2
  jest-html-reporters: ^3.1.7
  jest-junit: ^16.0.0
  jose: ^6.1.0
  jsdom: ^26.1.0
  lodash: ^4.17.21
  lucide-react: ^0.542.0
  moment: ^2.30.1
  nx: 21.4.1
  pixelmatch: ^7.1.0
  playwright-core: ^1.55.0
  pngjs: ^7.0.0
  postcss: ^8.4.31
  prettier: ^3.6.2
  react: ^19.1.1
  react-chartjs-2: ^5.3.0
  react-dom: ^19.1.1
  react-error-boundary: ^6.0.0
  react-router-dom: ^7.8.2
  rollup: ^4.50.0
  rollup-plugin-analyzer: ^4.0.0
  rollup-plugin-peer-deps-external: ^2.2.4
  rollup-plugin-postcss: ^4.0.2
  source-map: ^0.7.6
  stacktrace-parser: ^0.1.11
  tailwindcss: ^4.1.12
  ts-jest: ^29.4.1
  tslib: ^2.8.1
  typescript: ^5.9.2
  typescript-eslint: ^8.42.0
  use-sync-external-store: ^1.5.0
  vite: ^6.3.5
  vitest: ^3.2.4
  zustand: ^5.0.8
